### ISSUE TITLE
Select users by specific last name

### ISSUE THREAD

**Issue by siudzinski** [SzalatyM/sql-learning#2]
Select users whose last name starts with `B` and ends with `ski`. Display data sorted alphabetically by first name.
![image](https://user-images.githubusercontent.com/10303508/213304621-fe2374f1-c390-48dd-9448-0c1ab8d32c1a.png)

**Comment by SzalatyM** [comment]
SELECT * FROM `users` WHERE lastname LIKE 'B%ski'
ORDER BY firstname ASC
